name: Build WASM and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure Git for repository access
      run: |
        # Ensure we use HTTPS for GitHub access
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        # Set up authentication for private repos if needed
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/" || true
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Rust tests
      run: cargo test
      
    - name: Run Rust clippy
      run: cargo clippy -- -D warnings
      
    - name: Check Rust formatting
      run: cargo fmt --check
      
    - name: Build WASM package for web
      run: wasm-pack build --target web --out-dir pkg-web --dev
      
    - name: Build WASM package for bundlers
      run: wasm-pack build --target bundler --out-dir pkg --dev
      
    - name: Create Pages deployment directory
      run: |
        mkdir -p pages-deploy
        
    - name: Copy test files to deployment directory
      run: |
        cp -r test/ pages-deploy/
        cp -r pkg-web/ pages-deploy/
        
    - name: Create index.html for GitHub Pages
      run: |
        cat > pages-deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Comfy Table WASM - Test Suite</title>
            <style>
                body {
                    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
                    line-height: 1.6;
                    max-width: 1200px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: #f5f5f5;
                }
                
                h1 {
                    color: #333;
                    text-align: center;
                    border-bottom: 2px solid #007acc;
                    padding-bottom: 10px;
                }
                
                .container {
                    background: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                    text-align: center;
                }
                
                .button-container {
                    margin: 30px 0;
                }
                
                .btn {
                    display: inline-block;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    padding: 15px 30px;
                    text-decoration: none;
                    border-radius: 8px;
                    margin: 10px;
                    font-size: 18px;
                    font-weight: bold;
                    transition: transform 0.2s;
                }
                
                .btn:hover {
                    transform: translateY(-2px);
                }
                
                .description {
                    background: #e7f3ff;
                    border: 1px solid #b3d9ff;
                    border-radius: 8px;
                    padding: 20px;
                    margin: 20px 0;
                    text-align: left;
                }
                
                .features {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 20px;
                    margin: 30px 0;
                }
                
                .feature {
                    background: #f8f9fa;
                    padding: 20px;
                    border-radius: 8px;
                    border-left: 4px solid #007acc;
                }
                
                .feature h3 {
                    margin-top: 0;
                    color: #007acc;
                }
            </style>
        </head>
        <body>
            <h1>🚀 Comfy Table WASM Test Suite</h1>
            
            <div class="container">
                <div class="description">
                    <h2>📋 About This Test Suite</h2>
                    <p>This is a comprehensive test suite for the <strong>comfy-table-wasm</strong> library, a WebAssembly wrapper around the popular Rust <code>comfy-table</code> library for creating beautiful ASCII/UTF-8 tables.</p>
                    
                    <p>The test suite includes two main components:</p>
                    <ul>
                        <li><strong>Synchronized Tests:</strong> Exact reproductions of original comfy-table tests within WASM API constraints</li>
                        <li><strong>Extended Tests:</strong> Performance benchmarks, stress tests, edge cases, and unique scenarios</li>
                    </ul>
                    
                    <p>All tests include beautiful ANSI color formatting that gets converted to HTML for browser display!</p>
                </div>
                
                <div class="button-container">
                    <a href="test/comprehensive-test.html" class="btn">🧪 Run Interactive Test Suite</a>
                </div>
                
                <div class="features">
                    <div class="feature">
                        <h3>🎨 ANSI to HTML Conversion</h3>
                        <p>Advanced ANSI escape sequence conversion with support for colors, bold, underline, and background formatting.</p>
                    </div>
                    
                    <div class="feature">
                        <h3>⚡ Performance Testing</h3>
                        <p>Comprehensive performance benchmarks including large table creation, rendering, and memory stress tests.</p>
                    </div>
                    
                    <div class="feature">
                        <h3>🌍 Unicode Support</h3>
                        <p>Full Unicode and international character support with emoji, special symbols, and multilingual text.</p>
                    </div>
                    
                    <div class="feature">
                        <h3>🔍 Debug Tools</h3>
                        <p>Interactive debugging tools for failed tests with detailed analysis and visual output comparison.</p>
                    </div>
                </div>
                
                <div class="description">
                    <h3>🔗 Repository</h3>
                    <p>This test suite is automatically built and deployed from the GitHub repository. View the source code and contribute at:</p>
                    <p><a href="https://github.com/${GITHUB_REPOSITORY}" target="_blank">https://github.com/${GITHUB_REPOSITORY}</a></p>
                </div>
            </div>
        </body>
        </html>
        EOF
        
    - name: Replace GitHub repository placeholder
      run: |
        sed -i "s|\${GITHUB_REPOSITORY}|${{ github.repository }}|g" pages-deploy/index.html
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './pages-deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4